version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=task_management
      - JWT_SECRET=your-super-secret-key
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev # Use this for development to watch changes

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
