name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run Tests
      run: npm test
      env:
        CI: true
        # You might need to set up a test database service here
        # or mock the database connection for CI tests
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: password
        DB_DATABASE: test_db
        JWT_SECRET: test-secret
        JWT_REFRESH_SECRET: test-refresh-secret
